# Generated by Django 4.1.6 on 2023-02-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NewsApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="News",),
    ]
