# Generated by Django 4.1.6 on 2023-02-20 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("NewsApp", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="cover_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="images/"
            ),
            preserve_default=False,
        ),
    ]
